// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// alo_lasso_rcpp
List alo_lasso_rcpp(NumericMatrix A, NumericMatrix B, NumericVector y);
RcppExport SEXP _alocv_alo_lasso_rcpp(SEXP ASEXP, SEXP BSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(alo_lasso_rcpp(A, B, y));
    return rcpp_result_gen;
END_RCPP
}
// alo_enet_rcpp
List alo_enet_rcpp(NumericMatrix A, NumericMatrix B, NumericVector y, NumericVector lambda, double alpha, bool has_intercept, double tolerance, bool use_rfp);
RcppExport SEXP _alocv_alo_enet_rcpp(SEXP ASEXP, SEXP BSEXP, SEXP ySEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP has_interceptSEXP, SEXP toleranceSEXP, SEXP use_rfpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type has_intercept(has_interceptSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< bool >::type use_rfp(use_rfpSEXP);
    rcpp_result_gen = Rcpp::wrap(alo_enet_rcpp(A, B, y, lambda, alpha, has_intercept, tolerance, use_rfp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_alocv_alo_lasso_rcpp", (DL_FUNC) &_alocv_alo_lasso_rcpp, 3},
    {"_alocv_alo_enet_rcpp", (DL_FUNC) &_alocv_alo_enet_rcpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_alocv(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
