# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

alo_lasso_rcpp <- function(A, B, y, has_intercept = TRUE) {
    .Call('_alocv_alo_lasso_rcpp', PACKAGE = 'alocv', A, B, y, has_intercept)
}

alo_enet_rcpp <- function(A, B, y, lambda, family = 0L, alpha = 1.0, has_intercept = TRUE, a0 = NULL, tolerance = 1e-5, use_rfp = TRUE) {
    .Call('_alocv_alo_enet_rcpp', PACKAGE = 'alocv', A, B, y, lambda, family, alpha, has_intercept, a0, tolerance, use_rfp)
}

alo_svm_rcpp <- function(K, y, alpha, rho, lambda, tolerance = 1e-5, use_rfp = FALSE) {
    .Call('_alocv_alo_svm_rcpp', PACKAGE = 'alocv', K, y, alpha, rho, lambda, tolerance, use_rfp)
}

alo_svm_kernel <- function(X, kernel_type, gamma, degree, coef0, use_rfp = FALSE) {
    .Call('_alocv_alo_svm_kernel', PACKAGE = 'alocv', X, kernel_type, gamma, degree, coef0, use_rfp)
}

