# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

alo_lasso_rcpp <- function(A, B, y) {
    .Call('_alocv_alo_lasso_rcpp', PACKAGE = 'alocv', A, B, y)
}

alo_enet_rcpp <- function(A, B, y, lambda, alpha = 1.0, has_intercept = TRUE, a0 = NULL, tolerance = 1e-5, use_rfp = TRUE) {
    .Call('_alocv_alo_enet_rcpp', PACKAGE = 'alocv', A, B, y, lambda, alpha, has_intercept, a0, tolerance, use_rfp)
}

